sudo: required
language: scala

before_install:
- git clone git://github.com/jedisct1/libsodium.git
- cd libsodium
- git checkout 1.0.17
- ./autogen.sh
- ./configure && make check
- sudo make install
- sudo ldconfig
- cd ..
- sudo -E apt-get -yq --no-install-suggests --no-install-recommends install swig
- export PATH=${PATH}:./vendor/bundle

scala:
  - 2.13.0
  - 2.12.8
  - 2.11.12

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/libsodium

jdk:
  - openjdk8

install:
- rvm use 2.6.0 --install --fuzzy
- gem update --system
- gem install sass
- gem install jekyll -v 3.2.1

script:
  - bash sodium_setup.sh
  - sbt ++$TRAVIS_SCALA_VERSION clean
  - sbt ++$TRAVIS_SCALA_VERSION test
  - test $TRAVIS_SCALA_VERSION != "2.12.8" || sbt ++$TRAVIS_SCALA_VERSION tut
  - test $TRAVIS_SCALA_VERSION != "2.12.8" || sbt ++$TRAVIS_SCALA_VERSION microsite/makeMicrosite

after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_REPO_SLUG == "jmcardon/tsec" && sbt ++$TRAVIS_SCALA_VERSION publish
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_REPO_SLUG == "jmcardon/tsec" && test $TRAVIS_SCALA_VERSION == "2.12.8" && sbt ++$TRAVIS_SCALA_VERSION microsite/makeMicrosite

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: docs/target/site/
  target-branch: gh-pages
  on:
    branch: master
